import streamlit as st
import pandas as pd
import joblib


# ============================================================
# PAGE CONFIGURATION
# ============================================================

st.set_page_config(
    page_title="SwieeZone AI Business Intelligence",
    page_icon="🛍️",
    layout="wide"
)


# ============================================================
# LOAD DATA AND MODEL
# ============================================================

df = pd.read_csv("data/swieeZone_sales.csv")

df["Order_Date"] = pd.to_datetime(df["Order_Date"])

model = joblib.load("models/swieeZone_revenue_model.pkl")


# ============================================================
# HEADER
# ============================================================

st.title("🛍️ SwieeZone AI Business Intelligence")

st.markdown(
    "### 📊 AI-Powered Business Analytics & Revenue Intelligence"
)

st.write(
    "Monitor sales performance, discover business trends, "
    "identify opportunities, and generate AI-powered revenue predictions."
)

st.divider()


# ============================================================
# SIDEBAR FILTERS
# ============================================================

st.sidebar.header("🔎 Dashboard Filters")

category_filter = st.sidebar.selectbox(
    "Category",
    ["All"] + sorted(df["Category"].unique())
)

region_filter = st.sidebar.selectbox(
    "Region",
    ["All"] + sorted(df["Region"].unique())
)

payment_filter = st.sidebar.selectbox(
    "Payment Method",
    ["All"] + sorted(df["Payment_Method"].unique())
)

st.sidebar.divider()

st.sidebar.info(
    "Use the filters above to explore SwieeZone sales performance."
)


# ============================================================
# APPLY FILTERS
# ============================================================

filtered_df = df.copy()


if category_filter != "All":

    filtered_df = filtered_df[
        filtered_df["Category"] == category_filter
    ]


if region_filter != "All":

    filtered_df = filtered_df[
        filtered_df["Region"] == region_filter
    ]


if payment_filter != "All":

    filtered_df = filtered_df[
        filtered_df["Payment_Method"] == payment_filter
    ]


# ============================================================
# BUSINESS OVERVIEW
# ============================================================

total_orders = len(filtered_df)

total_revenue = filtered_df["Revenue"].sum()

average_order_value = (
    total_revenue / total_orders
    if total_orders > 0
    else 0
)

total_quantity = filtered_df["Quantity"].sum()


st.header("📌 Business Overview")


col1, col2, col3, col4 = st.columns(4)


with col1:

    st.metric(
        "📦 Total Orders",
        f"{total_orders:,}"
    )


with col2:

    st.metric(
        "💰 Total Revenue",
        f"₹{total_revenue:,.0f}"
    )


with col3:

    st.metric(
        "🛒 Average Order Value",
        f"₹{average_order_value:,.0f}"
    )


with col4:

    st.metric(
        "📊 Items Sold",
        f"{total_quantity:,}"
    )


st.divider()


# ============================================================
# EMPTY DATA CHECK
# ============================================================

if filtered_df.empty:

    st.warning(
        "⚠️ No sales data found for the selected filters. "
        "Please select different filters."
    )

else:

    # ========================================================
    # BUSINESS ANALYTICS
    # ========================================================

    st.header("📊 Business Analytics")

    st.write(
        "Understand revenue distribution across categories and regions."
    )


    col1, col2 = st.columns(2)


    # --------------------------------------------------------
    # CATEGORY REVENUE
    # --------------------------------------------------------

    with col1:

        st.subheader("🏷️ Revenue by Category")

        category_revenue = (
            filtered_df.groupby("Category")["Revenue"]
            .sum()
            .sort_values(ascending=False)
        )

        st.bar_chart(category_revenue)

        st.caption(
            "Revenue generated by each product category."
        )


    # --------------------------------------------------------
    # REGION REVENUE
    # --------------------------------------------------------

    with col2:

        st.subheader("🌎 Revenue by Region")

        region_revenue = (
            filtered_df.groupby("Region")["Revenue"]
            .sum()
            .sort_values(ascending=False)
        )

        st.bar_chart(region_revenue)

        st.caption(
            "Revenue contribution from different regions."
        )


    st.divider()


    # ========================================================
    # MONTHLY REVENUE TREND
    # ========================================================

    st.header("📈 Revenue Trend")

    st.write(
        "Track SwieeZone revenue performance throughout the year."
    )


    monthly_revenue = (
        filtered_df
        .set_index("Order_Date")
        .resample("ME")["Revenue"]
        .sum()
    )


    st.line_chart(monthly_revenue)

    st.caption(
        "Monthly revenue trend based on the selected filters."
    )


    st.divider()


    # ========================================================
    # PRODUCT PERFORMANCE
    # ========================================================

    st.header("🏆 Product Performance")

    st.write(
        "Identify the strongest and weakest products by revenue."
    )


    product_revenue = (
        filtered_df.groupby("Product")["Revenue"]
        .sum()
        .sort_values(ascending=False)
    )


    col1, col2 = st.columns(2)


    with col1:

        st.subheader("🥇 Top 10 Products")

        top_products = product_revenue.head(10)

        st.bar_chart(top_products)


    with col2:

        st.subheader("⚠️ Lowest Performing Products")

        bottom_products = product_revenue.tail(5).sort_values()

        st.bar_chart(bottom_products)


    st.divider()


    # ========================================================
    # PAYMENT METHOD ANALYSIS
    # ========================================================

    st.header("💳 Payment Method Analysis")

    st.write(
        "Analyze how customers pay and how much revenue each "
        "payment method generates."
    )


    payment_data = (
        filtered_df.groupby("Payment_Method")
        .agg(
            Orders=("Order_ID", "count"),
            Revenue=("Revenue", "sum")
        )
        .sort_values(
            "Revenue",
            ascending=False
        )
    )


    st.dataframe(
        payment_data,
        use_container_width=True
    )


    st.divider()


    # ========================================================
    # DISCOUNT ANALYSIS
    # ========================================================

    st.header("💰 Discount Analysis")

    st.write(
        "Understand how discounts are distributed across orders."
    )


    discount_analysis = (
        filtered_df.groupby("Discount")["Revenue"]
        .sum()
        .sort_index()
    )


    st.line_chart(discount_analysis)

    st.caption(
        "Revenue generated at different discount levels."
    )


    st.divider()


    # ========================================================
    # AI REVENUE PREDICTOR
    # ========================================================

    st.header("🤖 AI Revenue Predictor")

    st.write(
        "Enter order details and the trained machine-learning "
        "model will estimate the expected revenue."
    )


    col1, col2 = st.columns(2)


    with col1:

        product = st.selectbox(
            "Product",
            sorted(df["Product"].unique())
        )


        category = df.loc[
            df["Product"] == product,
            "Category"
        ].iloc[0]


        st.info(
            f"🏷️ Category: **{category}**"
        )


        quantity = st.number_input(
            "Quantity",
            min_value=1,
            max_value=20,
            value=1
        )


        price = st.number_input(
            "Price (₹)",
            min_value=100,
            max_value=10000,
            value=1000
        )


    with col2:

        discount = st.slider(
            "Discount (%)",
            min_value=0,
            max_value=50,
            value=10
        )


        region = st.selectbox(
            "Region",
            sorted(df["Region"].unique())
        )


        payment_method = st.selectbox(
            "Payment Method",
            sorted(df["Payment_Method"].unique())
        )


    if st.button("🔮 Predict Revenue"):

        input_data = pd.DataFrame(
            {
                "Product": [product],
                "Category": [category],
                "Quantity": [quantity],
                "Price": [price],
                "Discount": [discount],
                "Region": [region],
                "Payment_Method": [payment_method]
            }
        )


        prediction = model.predict(input_data)[0]


        st.success(
            f"💰 Predicted Revenue: ₹{prediction:,.2f}"
        )


    st.divider()


    # ========================================================
    # AI BUSINESS INTELLIGENCE
    # ========================================================

    st.header("🧠 AI Business Intelligence")

    st.write(
        "Automatically generated recommendations based on the "
        "selected sales data."
    )


    # --------------------------------------------------------
    # FIND TOP VALUES
    # --------------------------------------------------------

    top_product = product_revenue.index[0]

    top_product_revenue = product_revenue.iloc[0]


    top_category = category_revenue.index[0]

    top_category_revenue = category_revenue.iloc[0]


    top_region = region_revenue.index[0]

    top_region_revenue = region_revenue.iloc[0]


    top_payment = payment_data.index[0]


    # --------------------------------------------------------
    # RECOMMENDATION 1
    # --------------------------------------------------------

    st.success(
        f"🏆 **Product Recommendation:** "
        f"{top_product} is the highest-revenue product, "
        f"generating approximately ₹{top_product_revenue:,.0f}. "
        f"Consider maintaining strong inventory availability "
        f"for this product."
    )


    # --------------------------------------------------------
    # RECOMMENDATION 2
    # --------------------------------------------------------

    st.info(
        f"🏷️ **Category Recommendation:** "
        f"{top_category} is the strongest category with "
        f"approximately ₹{top_category_revenue:,.0f} in revenue. "
        f"Consider increasing marketing activity for this category."
    )


    # --------------------------------------------------------
    # RECOMMENDATION 3
    # --------------------------------------------------------

    st.warning(
        f"🌎 **Regional Recommendation:** "
        f"{top_region} is currently the strongest region, "
        f"contributing approximately ₹{top_region_revenue:,.0f}. "
        f"Consider exploring opportunities to improve performance "
        f"in other regions."
    )


    # --------------------------------------------------------
    # RECOMMENDATION 4
    # --------------------------------------------------------

    st.info(
        f"💳 **Payment Recommendation:** "
        f"{top_payment} generates the highest revenue among "
        f"the available payment methods. "
        f"Keep this payment option easily accessible to customers."
    )


    # --------------------------------------------------------
    # RECOMMENDATION 5
    # --------------------------------------------------------

    average_discount = filtered_df["Discount"].mean()


    if average_discount > 20:

        st.warning(
            f"💰 **Discount Alert:** "
            f"The average discount is {average_discount:.1f}%. "
            f"High discounts may reduce revenue margins. "
            f"Consider testing lower discount levels."
        )

    else:

        st.success(
            f"💰 **Discount Insight:** "
            f"The average discount is {average_discount:.1f}%. "
            f"Discount levels are currently within a moderate range."
        )


    st.divider()


    # ========================================================
    # DATA EXPLORER
    # ========================================================

    st.header("📋 Sales Data Explorer")

    st.write(
        "View the detailed sales records used by the dashboard."
    )


    st.dataframe(
        filtered_df,
        use_container_width=True
    )


    # ========================================================
    # DOWNLOAD DATA
    # ========================================================

    csv_data = filtered_df.to_csv(index=False).encode("utf-8")


    st.download_button(
        label="📥 Download Filtered Sales Data",
        data=csv_data,
        file_name="swieeZone_filtered_sales.csv",
        mime="text/csv"
    )


# ============================================================
# FOOTER
# ============================================================

st.divider()

st.caption(
    "SwieeZone AI Business Intelligence | "
    "Machine Learning + Data Analytics + Business Intelligence"
)